# -*- coding: utf-8 -*-
"""FirebaseColab

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18eQ3mxFniQ8GHyfsPVvX6-qWesNQ0H0I
"""

import numpy as np
import os

from tflite_model_maker import configs
from tflite_model_maker import ExportFormat
from tflite_model_maker import model_spec
from tflite_model_maker import text_classifier
from tflite_model_maker.text_classifier import DataLoader

import tensorflow as tf
assert tf.__version__.startswith('2')

data_dir = tf.keras.utils.get_file(
      fname='SST-2.zip',
      origin='https://dl.fbaipublicfiles.com/glue/data/SST-2.zip',
      extract=True)
data_dir = os.path.join(os.path.dirname(data_dir), 'SST-2')

awv_spec = model_spec.get('average_word_vec')

awv_train_data = DataLoader.from_csv(
      filename=os.path.join(os.path.join(data_dir, 'train.tsv')),
      text_column='sentence',
      label_column='label',
      model_spec=awv_spec,
      delimiter='\t',
      is_training=True)
awv_test_data = DataLoader.from_csv(
      filename=os.path.join(os.path.join(data_dir, 'dev.tsv')),
      text_column='sentence',
      label_column='label',
      model_spec=awv_spec,
      delimiter='\t',
      is_training=False)

awv_model = text_classifier.create(awv_train_data, model_spec=awv_spec, epochs=10)

awv_model.evaluate(awv_test_data)

awv_model.export(export_dir='average_word_vec/')

!cp average_word_vec/model.tflite sentiment_analysis.tflite

from google.colab import files
files.download('sentiment_analysis.tflite')